---
name: Audio-MPD
version: 0.18.0
author: []
abstract: class to talk to MPD (Music Player Daemon) servers
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Audio::MPD::Common: 0
  Class::Accessor: 0
  Encode: 0
  IO::Socket: 0
  Readonly: 0
  Scalar::Util: 0
  perl: 5.8.0
build_requires:
  Test::More: 0
  perl: 5.8.0
provides:
  Audio::MPD:
    file: lib/Audio/MPD.pm
    version: 0.18.0
  Audio::MPD::Collection:
    file: lib/Audio/MPD/Collection.pm
  Audio::MPD::Playlist:
    file: lib/Audio/MPD/Playlist.pm
  Audio::MPD::Test:
    file: lib/Audio/MPD/Test.pm
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
