---
name: Audio-MPD
version: 0.13.0
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
  - |-
    Original code by Tue Abrahamsen <tue.abrahamsen@gmail.com>, documented by
    Nicholas J. Humfrey <njh@aelius.com>.
abstract: Class for talking to MPD (Music Player Daemon) servers
license: gpl
resources:
  license: http://www.opensource.org/licenses/gpl-license.php
requires:
  IO::Socket: 1.00
  Test: 1.00
build_requires:
  Module::Build: 0.20
provides:
  Audio::MPD:
    file: lib/Audio/MPD.pm
    version: 0.13.0
  Audio::MPD::Test:
    file: lib/Audio/MPD/Test.pm
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
