---
name: Audio-MPD
version: 0.19.6
author:
  - 'Jerome Quelin, C<< <jquelin@cpan.org> >>'
  - |-
    Original code by Tue Abrahamsen C<< <tue.abrahamsen@gmail.com> >>,
    documented by Nicholas J. Humfrey C<< <njh@aelius.com> >>.
abstract: class to talk to MPD (Music Player Daemon) servers
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Audio::MPD::Common: 0
  Class::Accessor::Fast: 0
  DB_File: 0
  Encode: 0
  Getopt::Euclid: 0
  IO::Socket: 0
  Proc::Daemon: 0
  Readonly: 0
  Scalar::Util: 0
  Time::HiRes: 0
  perl: 5.008
build_requires:
  Audio::MPD::Common: 0
  Class::Accessor::Fast: 0
  DB_File: 0
  Encode: 0
  Getopt::Euclid: 0
  IO::Socket: 0
  Proc::Daemon: 0
  Readonly: 0
  Scalar::Util: 0
  Test::More: 0
  Time::HiRes: 0
  perl: 5.008
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Audio::MPD:
    file: lib/Audio/MPD.pm
    version: 0.19.6
  Audio::MPD::Collection:
    file: lib/Audio/MPD/Collection.pm
  Audio::MPD::Playlist:
    file: lib/Audio/MPD/Playlist.pm
  Audio::MPD::Test:
    file: lib/Audio/MPD/Test.pm
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
