---
name: Audio-MPD
version: 0.17.0
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
  - |-
    Original code by Tue Abrahamsen <tue.abrahamsen@gmail.com>, documented by
    Nicholas J. Humfrey <njh@aelius.com>.
abstract: class to talk to MPD (Music Player Daemon) servers
license: gpl
resources:
  license: http://www.opensource.org/licenses/gpl-license.php
requires:
  Class::Accessor: 0
  Encode: 0
  IO::Socket: 0
  Readonly: 0
  Scalar::Util: 0
  perl: 5.8.0
build_requires:
  Test::More: 0
  perl: 5.8.0
provides:
  Audio::MPD:
    file: lib/Audio/MPD.pm
    version: 0.17.0
  Audio::MPD::Collection:
    file: lib/Audio/MPD/Collection.pm
  Audio::MPD::Item:
    file: lib/Audio/MPD/Item.pm
  Audio::MPD::Item::Directory:
    file: lib/Audio/MPD/Item/Directory.pm
  Audio::MPD::Item::Song:
    file: lib/Audio/MPD/Item/Song.pm
  Audio::MPD::Playlist:
    file: lib/Audio/MPD/Playlist.pm
  Audio::MPD::Status:
    file: lib/Audio/MPD/Status.pm
  Audio::MPD::Test:
    file: lib/Audio/MPD/Test.pm
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
